theme: jekyll-theme-cayman
title: Norbert Ledényi
description: I work with data. Sometimes I write code. Or create data visualizations. In my spare time I 3D model and print. Or play with some ESP, Arduino or Raspberry Pi devices. Oh and there is smarthome with Home Assistatant and Z-wave. I also like sim racing.
google_analytics: UA-72533755-3